/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CardTemplateSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'designJson',
    'eventId',
    'height',
    'id',
    'name',
    'updatedAt',
    'width',
  ] as const
  $columns = CardTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare designJson: any
  @column()
  declare eventId: number
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number
}

export class EmailSettingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'credentials',
    'fromEmail',
    'fromName',
    'id',
    'isVerified',
    'lastTestedAt',
    'provider',
    'updatedAt',
    'userId',
  ] as const
  $columns = EmailSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentials: string
  @column()
  declare fromEmail: string
  @column()
  declare fromName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerified: boolean
  @column.dateTime()
  declare lastTestedAt: DateTime | null
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class EventSchema extends BaseModel {
  static $columns = [
    'allowPublicRsvp',
    'createdAt',
    'description',
    'endsAt',
    'id',
    'location',
    'slug',
    'startsAt',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = EventSchema.$columns
  @column()
  declare allowPublicRsvp: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string | null
  @column()
  declare slug: string
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class GuestSchema extends BaseModel {
  static $columns = [
    'checkedInAt',
    'checkedInById',
    'createdAt',
    'email',
    'eventId',
    'id',
    'name',
    'phone',
    'rsvpStatus',
    'updatedAt',
  ] as const
  $columns = GuestSchema.$columns
  @column.dateTime()
  declare checkedInAt: DateTime | null
  @column()
  declare checkedInById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare rsvpStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvitationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'eventId',
    'guestId',
    'id',
    'method',
    'scannedAt',
    'sentAt',
    'status',
    'token',
    'updatedAt',
    'viewedAt',
  ] as const
  $columns = InvitationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: number
  @column()
  declare guestId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare method: string
  @column.dateTime()
  declare scannedAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare viewedAt: DateTime | null
}

export class TemplatePresetSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'designJson',
    'height',
    'id',
    'isPublished',
    'name',
    'previewImage',
    'updatedAt',
    'width',
  ] as const
  $columns = TemplatePresetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare designJson: any
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPublished: boolean
  @column()
  declare name: string
  @column()
  declare previewImage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'firebaseUid',
    'fullName',
    'id',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firebaseUid: string | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
